const LIST_OF_IMAGE_CATEGORIES = {
  en: ['People', 'Media', 'Camps', 'Other'],
  cn: ['人们', '媒体', '营地', '其他'],
};

const ETHNIC_GROUP_CONSTANTS = {
  en: [
    'Zhuang',
    'Hui',
    'Han',
    'Manchu',
    'Uyghur',
    'Miao',
    'Yi',
    'Tujia',
    'Tibetan',
    'Mongol',
    'Dong',
    'Bouyei',
    'Yao',
    'Bai',
    'Joseonjok',
    'Hani',
    'Li',
    'Kazakh',
    'Dai',
    'She',
    'Lisu',
    'Dongxiang',
    'Gelao',
    'Lahu',
    'Wa',
    'Sui',
    'Nakhi',
    'Qiang',
    'Tu',
    'Mulao',
    'Xibe',
    'Kyrgyz',
    'Jingpo',
    'Daur',
    'Salar',
    'Blang',
    'Maonan',
    'Tajik',
    'Pumi',
    'Achang',
    'Nu',
    'Evenki',
    'Vietnamese',
    'Jino',
    'De ang',
    'Bonan',
    'Russian',
    'Yugur',
    'Uzbek',
    'Monba',
    'Oroqen',
    'Derung',
    'Hezhen',
    'Gaoshan',
    'Lhoba',
    'Tatars',
    'Undistinguished',
    'Naturalized Citizen',
  ],
  cn: [
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
    '未知',
  ],
};

const LIST_OF_GENDER = {
  en: ['male', 'female', 'unknown'],
  cn: ['男性', '女性', '未知'],
};

const LIST_OF_STATUS = {
  en: ['alive', 'deceased', 'unknown'],
  cn: ['活', '死者', '未知'],
};

export { ETHNIC_GROUP_CONSTANTS, LIST_OF_GENDER, LIST_OF_STATUS, LIST_OF_IMAGE_CATEGORIES };
