export const NavBar = [
    {
        title: 'Home',
        url: '/home',
        icon: 'home',
        isCollapsed: true,
        isActive: false,
    },
    {
        title: 'Browse',
        url: '/browse',
        icon: 'home',
        isCollapsed: true,
        isActive: false,
    },
    {
        title: 'About',
        url: '/about',
        icon: 'info',
        isCollapsed: true,
        isActive: false,
    },
    {
        title: 'Gallery',
        url: '/gallery',
        icon: 'phone',
        isCollapsed: true,
        isActive: false,
    },
    {
        title: 'Log In',
        url: '/login',
        icon: 'user',
        isCollapsed: true,
        isActive: false,
    },
    // {
    //     title: 'Register',
    //     url: '/register',
    //     icon: 'user-plus',
    //     isCollapsed: true,
    //     isActive: false,
    // },
    // {
    //     title: 'Dashboard',
    //     url: '/dashboard',
    //     icon: 'dashboard',
    //     isCollapsed: true,
    //     isActive: false,
    // },
    // {
    //     title: 'Profile',
    //     url: '/profile',
    //     icon: 'user-circle',
    //     isCollapsed: true,
    //     isActive: false,
    // },
    // {
    //     title: 'Settings',
    //     url: '/settings',
    //     icon: 'cog',
    //     isCollapsed: true,
    //     isActive: false,
    // },
    // {
    //     title: 'Logout',
    //     url: '/logout',
    //     icon: 'sign-out-alt',
    //     isCollapsed: true,
    //     isActive: false,
    // },
];