export const GROUPS = [
  { value: '1', viewValue: 'Han' },
  { value: '2', viewValue: 'Zhuang' },
  { value: '3', viewValue: 'Hui' },
  { value: '4', viewValue: 'Manchu' },
  { value: '5', viewValue: 'Uyghur' },
  { value: '6', viewValue: 'Miao' },
  { value: '7', viewValue: 'Yi' },
  { value: '8', viewValue: 'Tujia' },
  { value: '9', viewValue: 'Tibetan' },
  { value: '10', viewValue: 'Mongol' },
  { value: '11', viewValue: 'Dong' },
  { value: '12', viewValue: 'Bouyei' },
  { value: '13', viewValue: 'Yao' },
  { value: '14', viewValue: 'Bai' },
  { value: '15', viewValue: 'Joseonjok' },
  { value: '16', viewValue: 'Hani' },
  { value: '17', viewValue: 'Li' },
  { value: '18', viewValue: 'Kazakh' },
  { value: '19', viewValue: 'Dai' },
  { value: '20', viewValue: 'She' },
  { value: '21', viewValue: 'Lisu' },
  { value: '22', viewValue: 'Dongxiang' },
  { value: '23', viewValue: 'Gelao' },
  { value: '24', viewValue: 'Lahu' },
  { value: '25', viewValue: 'Wa' },
  { value: '26', viewValue: 'Sui' },
  { value: '27', viewValue: 'Nakhi' },
  { value: '28', viewValue: 'Qiang' },
  { value: '29', viewValue: 'Tu' },
  { value: '30', viewValue: 'Mulao' },
  { value: '31', viewValue: 'Xibe' },
  { value: '32', viewValue: 'Kyrgyz' },
  { value: '33', viewValue: 'Jingpo' },
  { value: '34', viewValue: 'Daur' },
  { value: '35', viewValue: 'Salar' },
  { value: '36', viewValue: 'Blang' },
  { value: '37', viewValue: 'Maonan' },
  { value: '38', viewValue: 'Tajik' },
  { value: '39', viewValue: 'Pumi' },
  { value: '40', viewValue: 'Achang' },
  { value: '41', viewValue: 'Nu' },
  { value: '42', viewValue: 'Evenki' },
  { value: '43', viewValue: 'Vietnamese' },
  { value: '44', viewValue: 'Jino' },
  { value: '45', viewValue: 'De ang' },
  { value: '46', viewValue: 'Bonan' },
  { value: '47', viewValue: 'Russian' },
  { value: '48', viewValue: 'Yugur' },
  { value: '49', viewValue: 'Uzbek' },
  { value: '50', viewValue: 'Monba' },
  { value: '51', viewValue: 'Oroqen' },
  { value: '52', viewValue: 'Derung' },
  { value: '53', viewValue: 'Hezhen' },
  { value: '54', viewValue: 'Gaoshan' },
  { value: '55', viewValue: 'Lhoba' },
  { value: '56', viewValue: 'Tatars' },
  { value: '57', viewValue: 'Unknown' },
  { value: '58', viewValue: 'Naturalized Citizen' },
];



export const OCCUPATIONS = [
  { value: '1', viewValue: 'Deputy' },
  { value: '2', viewValue: 'Director' },
  { value: '3', viewValue: 'Professor' },
  { value: '4', viewValue: 'Worker' },
  { value: '5', viewValue: 'Actress' },
  { value: '6', viewValue: 'Agent' },
  { value: '7', viewValue: 'Assistant' },
  { value: '8', viewValue: 'Editor-in-Chief' },
  { value: '9', viewValue: 'Assistant Lieutenant' },
  { value: '10', viewValue: 'Assistant Professor' },
  { value: '11', viewValue: 'Associate Professor' },
  { value: '12', viewValue: 'Cadre' },
  { value: '13', viewValue: 'Chairman' },
  { value: '14', viewValue: 'Chief' },
  { value: '15', viewValue: 'Chief Engineer' },
  { value: '16', viewValue: 'Christian Priest' },
  { value: '17', viewValue: 'Clerk' },
  { value: '18', viewValue: 'Deputy Director' },
  { value: '19', viewValue: 'Deputy Secretary' },
  { value: '20', viewValue: 'Deputy Secretary General' },
  { value: '21', viewValue: 'Doctor' },
  { value: '22', viewValue: 'Editor' },
  { value: '23', viewValue: 'Editorial Editor' },
  { value: '24', viewValue: 'Faculty' },
  { value: '25', viewValue: 'Governor' },
  { value: '26', viewValue: 'Graduate' },
  { value: '27', viewValue: 'Head' },
  { value: '28', viewValue: 'Internship Researcher' },
  { value: '29', viewValue: 'Lieutenant Staff Officer' },
  { value: '30', viewValue: 'Manager' },
  { value: '31', viewValue: 'Member' },
  { value: '32', viewValue: 'Ministry' },
  { value: '33', viewValue: 'Officer' },
  { value: '34', viewValue: 'Painter' },
  { value: '35', viewValue: 'Peasant' },
  { value: '36', viewValue: 'Pilot' },
  { value: '37', viewValue: 'President' },
  { value: '38', viewValue: 'Principal' },
  { value: '39', viewValue: 'Reader' },
  { value: '40', viewValue: 'Research Intern' },
  { value: '41', viewValue: 'Secretary' },
  { value: '42', viewValue: 'Staff' },
  { value: '43', viewValue: 'Student' },
  { value: '44', viewValue: 'Teacher' },
  { value: '45', viewValue: 'Technician' },
  { value: '46', viewValue: 'Trainee' },
  { value: '47', viewValue: 'Vice Chairman' },
  { value: '48', viewValue: 'Vice Dean' },
  { value: '49', viewValue: 'Vice President' },
  { value: '50', viewValue: 'Vice Principal' },
  { value: '51', viewValue: 'Writer' },
  { value: '52', viewValue: 'Unknown' },
];